name: speedy_feast
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: 4.6.6
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/intro.jpeg
    - images/google-plus.svg
